const DEFAULT_NOTIFICATION_SWEEP_CRON_EXPRESSION = '0 * * * * *';
const DEFAULT_NOTIFICATION_SWEEP_PENDING_THRESHOLD_MS = 120000;
const DEFAULT_NOTIFICATION_SWEEP_MAX_ATTEMPTS = 3;

function resolvePositiveInt(envName: string, defaultValue: number): number {
  const parsed = parseInt(process.env[envName] ?? '', 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : defaultValue;
}

export const NOTIFICATION_SWEEP_CRON_EXPRESSION =
  process.env.NOTIFICATION_SWEEP_CRON_EXPRESSION ??
  DEFAULT_NOTIFICATION_SWEEP_CRON_EXPRESSION;

export const NOTIFICATION_SWEEP_PENDING_THRESHOLD_MS = resolvePositiveInt(
  'NOTIFICATION_SWEEP_PENDING_THRESHOLD_MS',
  DEFAULT_NOTIFICATION_SWEEP_PENDING_THRESHOLD_MS
);

export const NOTIFICATION_SWEEP_MAX_ATTEMPTS = resolvePositiveInt(
  'NOTIFICATION_SWEEP_MAX_ATTEMPTS',
  DEFAULT_NOTIFICATION_SWEEP_MAX_ATTEMPTS
);
