const DEFAULT_OFFENSIVE_DEACTIVATION_CRON_EXPRESSION = '0 */5 * * * *';

export const OFFENSIVE_DEACTIVATION_CRON_EXPRESSION =
  process.env.OFFENSIVE_DEACTIVATION_CRON_EXPRESSION ??
  DEFAULT_OFFENSIVE_DEACTIVATION_CRON_EXPRESSION;