const DEFAULT_TESLA_TOKEN_REFRESH_CRON_EXPRESSION = '0 0 2 * * *';

export const TESLA_TOKEN_REFRESH_CRON_EXPRESSION =
  process.env.TESLA_TOKEN_REFRESH_CRON_EXPRESSION ??
  DEFAULT_TESLA_TOKEN_REFRESH_CRON_EXPRESSION;
